### ISSUE TITLE
Et Futurum is not dead. Switch to using its successer, Et Futurum Requiem.

### ISSUE THREAD

**Issue by MagmaSlime123** [sky0-1/Et-Futurum-Golems-Addon-1.7.10#1]
Title.

https://www.curseforge.com/minecraft/mc-mods/et-futurum-requiem

If this is dead, remove it.

**Comment by skyjay1** [comment]
Extra Golems is no longer receiving updates for versions older than 1.16.5. I apologize for the inconvenience.
